name: Lint with Ruff and Black, build Docker image

on:
  - push
  - pull_request

jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12"]
        poetry-version: ["1.6.1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Configure Poetry to use local virtualenv
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Cache local virtualenv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install project dependencies
        run: poetry install --without dev --no-root --no-directory

      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: "--config ./pyproject.toml"
          src: "./src"

      - name: Lint with Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"

  docker_build:
    runs-on: ubuntu-latest
    # Don't try to build the Docker image unless linting succeeds
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag linkfix-for-discord:$(date +%s)
